### PR TITLE
C

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit b591fee has been approved by `barosl2`

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
[separator]

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit b591fee with merge c21cd6d...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85481999)

**Pull request merged**
