### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit f780975 has been approved by `barosl2`

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/88896978)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #112) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
