### PR TITLE
p

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit d98772f has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit d98772f with merge dc7b0d1...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84410043)

**Pull request merged**
