### PR TITLE
b

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit c8993d1 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit c8993d1 with merge 0c3c0e0...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/83192506)

**Pull request closed without merging**
