### PR TITLE
a

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 2326d78 has been approved by `barosl2`

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/90981654)

**Comment by barosl3** [comment]
:boom: Failed to recover from the artificial commit. See d53898448ed3d8f97acb92173eb6a4846f5bd265 for details.

**Pull request merged**
