### PR TITLE
i

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 751f700 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 751f700 with merge 7d6b150...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/83199697)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #42) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
