### PR TITLE
g

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 5fa79d6 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 5fa79d6 with merge e8dff05...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91119529)

**Pull request merged**
