### PR TITLE
D

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 0854ee3 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 0854ee3 with merge 1613eb1...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/89113014)

**Pull request merged**
