### PR TITLE
final2

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit da70e74 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit da70e74 with merge 2ab43b5...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/83046434)

**Comment by barosl3** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Reference already exists

**Pull request closed without merging**
