### PR TITLE
more

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pill: [DEBUG] head_sha reset from 0000 to 90690d47a2a50c0e6f5d7dc5ec2f281c148d7626

**Comment by barosl3** [comment]
:pushpin: Commit 90690d4 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 90690d4 with merge 32dc8cb...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/77832042)

**Pull request merged**
