### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 6210495 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 6210495 with merge 38db641...

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit e09bfec has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit e09bfec with merge 496ead1...

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 5d5c9c9 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 5d5c9c9 with merge aeeeb47...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/103117194)

**Pull request merged**
