### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 6fded9b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 6fded9b with merge 31f1c0a...

**Comment by barosl3** [comment]
:boom: Test timed out

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/92466641)

**Pull request merged**
