### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 1ca35d2 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 1ca35d2 with merge b725710...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/89368851)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #130) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
