### PR TITLE
A

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit ecffc61 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit ecffc61 with merge 399d6c3...

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit ecffc61 has been approved by `barosl2`

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 rery

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit ecffc61 with merge a8fe993...

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit a8fe993 has been approved by `barosl2`

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit ecffc61 with merge 4f047a2...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85479391)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #57) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
