### PR TITLE
h

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 6a3dc57 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 6a3dc57 with merge 3bbc8fb...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91190441)

**Pull request merged**
