### PR TITLE
e

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 10a4517 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 10a4517 with merge bd788b3...

**Comment by barosl3** [comment]
:sunny: Test exempt - [status](https://travis-ci.org/barosl2/test4/builds/88857525)

**Pull request merged**
