### PR TITLE
g

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit c9a9014 has been approved by `barosl2`

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit c9a9014 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit c9a9014 with merge 74e9fec...

**Comment by barosl2** [comment]
@barosl4 retry

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit c9a9014 with merge a426870...

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88209321)

**Comment by barosl3** [comment]
:hourglass: Testing commit c9a9014 with merge 0f43528...

**Pull request merged**
