### PR TITLE
o

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 85960eb has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 85960eb with merge 3079cb9...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84409820)

**Pull request merged**
