### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 4a26f87 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 4a26f87 with merge e06b5f1...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/89766096)

**Comment by barosl3** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Reference update failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/89766083)

**Pull request merged**
