### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit a4b80bd has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit a4b80bd with merge 434943a...

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/93645713)

**Pull request merged**
