### PR TITLE
A

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit ba1e178 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit ba1e178 with merge 5510fc5...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88909521)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #114) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
