### PR TITLE
final1

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 7befe4e has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 7befe4e with merge 38a0ab1...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/83046415)

**Pull request merged**
