### PR TITLE
i

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 9fd5706 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 9fd5706 with merge 36aab5b...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88228786)

**Pull request merged**
