### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit a49d132 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit a49d132 with merge 05abc8d...

**Comment by barosl3** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/barosl2/test4/builds/88224322)

**Pull request merged**
