### PR TITLE
E

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit cb76178 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit cb76178 with merge 474bb2a...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88911351)

**Pull request merged**
