### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 1adb7a9 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 1adb7a9 with merge db17186...

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:bulb: This pull request was already approved, no need to approve it again.
- There's another pull request that is currently being tested, blocking this pull request: #338

**Comment by barosl3** [comment]
:broken_heart: Test failed - [status](https://travis-ci.org/barosl2/test4/builds/92794069)

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:bulb: This pull request was already approved, no need to approve it again.
- You may use `retry` to test a failed pull request again.
- There's another pull request that is currently being tested, blocking this pull request: #337

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:bulb: This pull request was already approved, no need to approve it again.
- You may use `retry` to test a failed pull request again.

**Pull request closed without merging**
