### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 82f3812 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 82f3812 with merge 6df49ad...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/90982967)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably 6df49ad) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
