### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit b6cd334 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit b6cd334 with merge e9bc6b7...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91142178)

**Pull request merged**
