### PR TITLE
p

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit f1b1434 has been approved by `barosl2`

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/90928302)

**Comment by barosl3** [comment]
:boom: Failed to recover from the artificial commit. See af748a7511b513fe89ccb1cc827bd45817b427b3 for details.

**Pull request merged**
