### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 01589eb has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 01589eb with merge a80a905...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91191700)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably a80a905) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
