### PR TITLE
l

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 4a2bddc has been approved by `barosl2`

**Comment by barosl3** [comment]
:lock: Merge conflict

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit 4a2bddc with merge fe9ba1c...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91081882)

**Pull request merged**
