### PR TITLE
B

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit fb8da1a has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit fb8da1a with merge 8f1975f...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85479889)

**Pull request merged**
