### PR TITLE
k

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit de1dbe3 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit de1dbe3 with merge e06e247...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88229691)

**Pull request merged**
