### PR TITLE
b

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably f8e3dbb) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 024e796 has been approved by `barosl2`

**Comment by barosl3** [comment]
:lock: Merge conflict

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Merge conflict

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit ff08bc2 has been approved by `barosl2`

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 8b7492b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 8b7492b with merge 56e0476...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85033068)

**Pull request merged**
