### PR TITLE
j

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit f30eff0 has been approved by `barosl2`

**Comment by barosl3** [comment]
:lock: Merge conflict

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit f30eff0 with merge 78b23c1...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91097801)

**Pull request merged**
