### PR TITLE
a

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 14bf2b5 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 14bf2b5 with merge 69d8a68...

**Comment by barosl3** [comment]
:sunny: Test exempt - [status](https://travis-ci.org/barosl2/test4/builds/88853001)

**Pull request merged**
