### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 17dbda0 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 17dbda0 with merge 6ddb796...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/83195944)

**Pull request closed without merging**
