### PR TITLE
r

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 0a0d04b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 0a0d04b with merge 7d345ff...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84410663)

**Pull request merged**
