### PR TITLE
e

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 8334f5b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 8334f5b with merge 4f2b44a...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/89766329)

**Comment by barosl3** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Reference update failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 8334f5b has been approved by `barosl2`

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/89766313)

**Pull request merged**
