### PR TITLE
a

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:bangbang: Invalid head SHA found, retrying: `0000`

**Comment by barosl3** [comment]
:pushpin: Commit 09a3fce has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 09a3fce with merge a2f6e76...

**Comment by barosl2** [comment]
aefae ae aefae

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:bangbang: Invalid head SHA found, retrying: `0000`

**Comment by barosl3** [comment]
:pushpin: Commit a99ef9f has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit a99ef9f with merge 55bf613...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/77941806)

**Pull request merged**
