### PR TITLE
g

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 3fecae8 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 3fecae8 with merge 438e868...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/90906008)

**Comment by barosl3** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Reference update failed

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 3fecae8 has been approved by `barosl2`

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/90905976)

**Pull request merged**
