### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 6d16e0b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 6d16e0b with merge 4311b5d...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91194376)

**Pull request merged**
