### PR TITLE
E

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 1e48c0c has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 1e48c0c with merge 41757e8...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85482962)

**Pull request merged**
