### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 2d1367e has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 2d1367e with merge 019b23f...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88887222)

**Pull request merged**
