### PR TITLE
f

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit e506b7a has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit e506b7a with merge c306c7c...

**Comment by barosl3** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/barosl2/test4/builds/88228318)

**Pull request merged**
