### PR TITLE
A

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 0e47b32 has been approved by `barosl2`

**Comment by barosl3** [comment]
:lock: Merge conflict

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Merge conflict

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:lock: Auto-squashing failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit a2fbdee has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit a2fbdee with merge 3912f60...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85031746)

**Pull request merged**
