### PR TITLE
T

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 0fd0edb has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 0fd0edb with merge 50d7662...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84411858)

**Pull request merged**
