### PR TITLE
e

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit bb89f6b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit bb89f6b with merge d54e403...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91195020)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably d54e403) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
