### PR TITLE
C

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 18d84d8 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 18d84d8 with merge c74ab99...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/85033480)

**Pull request merged**
