### PR TITLE
e

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit a8b58b2 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit a8b58b2 with merge 373f78d...

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit a8b58b2 with merge 65d2d25...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/102468013)

**Pull request merged**
