### PR TITLE
n

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 106af30 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 106af30 with merge 6698220...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84409300)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #47) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
