### PR TITLE
g

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit b957a47 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit b957a47 with merge e646995...

**Comment by barosl3** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/barosl2/test4/builds/88228556)

**Pull request merged**
