### PR TITLE
g

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 623eab3 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 623eab3 with merge c06ab0c...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91142580)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably c06ab0c) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
