### PR TITLE
b

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit e1e3ffb has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit e1e3ffb with merge 0695860...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91132121)

**Pull request merged**
