### PR TITLE
h

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 42cf8e9 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 42cf8e9 with merge d03cbe3...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88229431)

**Pull request merged**
