### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit cdd3ade has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit cdd3ade with merge b620357...

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit cdd3ade with merge d32ff4f...

**Comment by barosl3** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/barosl2/test4/builds/88224146)

**Pull request merged**
