### PR TITLE
g

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 8c12d62 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 8c12d62 with merge 6446cc1...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88863954)

**Pull request merged**
