### PR TITLE
d

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit d171c8e has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit d171c8e with merge ba6a9d5...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88782800)

**Pull request merged**
