### PR TITLE
i

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit ea51a09 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit ea51a09 with merge 0d59ff3...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/90911724)

**Comment by barosl3** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Reference update failed

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:zap: Test exempted - [status](https://travis-ci.org/barosl2/test4/builds/90911693)

**Pull request merged**
