### PR TITLE
j

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 4b2d7cd has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 4b2d7cd with merge ea10643...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84401491)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably #43) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
