### PR TITLE
b

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 10a58db has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 10a58db with merge cb54bdc...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91118668)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably cb54bdc) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
