### PR TITLE
i

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 3d2d251 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 3d2d251 with merge 2ccb4f9...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91142930)

**Pull request merged**
