### PR TITLE
o

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 6a4c55c has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 6a4c55c with merge 42753f9...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/90928120)

**Comment by barosl3** [comment]
:boom: Failed to recover from the artificial commit. See 6d7a79d17ab83f1a2e9a32d557802164791559d3 for details.

**Pull request merged**
