### PR TITLE
j

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 6ff89c2 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 6ff89c2 with merge eb9fc33...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88229290)

**Pull request merged**
