### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 29b2c2b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 29b2c2b with merge a502f9e...

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 1e7f33e has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 1e7f33e with merge 1ed75bb...

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 0c04e8b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 0c04e8b with merge b4389cc...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/103116093)

**Pull request merged**
