### PR TITLE
b

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 1e9a45f has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 1e9a45f with merge 91fbc27...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/91189992)

**Comment by barosl3** [comment]
:umbrella: The latest upstream changes (presumably 91fbc27) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
