### PR TITLE
e

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 07cacf7 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 07cacf7 with merge ddc6ffd...

**Comment by barosl3** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/barosl2/test4/builds/88228005)

**Pull request merged**
