### PR TITLE
j

### PR DESCRIPTION
**Pull request by barosl2**
@barosl3 r+

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 2ed7591 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 2ed7591 with merge ff3b728...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/89745710)

**Pull request merged**
