### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 1c3859c has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 1c3859c with merge ea3846c...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/71853837)

**Pull request merged**
