### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit ba4ab25 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit ba4ab25 with merge 059a4c0...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/93606532)

**Pull request merged**
