### PR TITLE
B

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 66686ab has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 66686ab with merge 9d8ea50...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/89112225)

**Pull request merged**
