### PR TITLE
s

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit baf9a8a has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit baf9a8a with merge 1de004f...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/84410963)

**Pull request merged**
