### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 5a70c72 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 5a70c72 with merge ace410c...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/88781625)

**Pull request merged**
