### PR TITLE
a

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 869a8b9 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 869a8b9 with merge d595353...

**Comment by barosl2** [comment]
@barosl3 retry

**Comment by barosl3** [comment]
:hourglass: Testing commit 869a8b9 with merge 4d362e8...

**Comment by barosl3** [comment]
:sunny: Test exempt - [status](https://travis-ci.org/barosl2/test4/builds/88558405)

**Pull request merged**
