### PR TITLE
Rollup of 1 pull requests

### PR DESCRIPTION
**Pull request by barosl2**
- Successful merges: #21
- Failed merges: #22

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl2** [comment]
abc

**Comment by barosl2** [comment]
daefaf

**Comment by barosl2** [comment]
haha

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 2e3af8b has been approved by `barosl2`

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pill: [DEBUG] head_sha reset from 0000 to 2e3af8b96e5e147ea5c961dbcc08686818d2583d

**Comment by barosl3** [comment]
:pushpin: Commit 2e3af8b has been approved by `barosl2`

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pill: [DEBUG] head_sha reset from 0000 to 2e3af8b96e5e147ea5c961dbcc08686818d2583d

**Comment by barosl3** [comment]
:pushpin: Commit 2e3af8b has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 2e3af8b with merge 39c89f9...

**Comment by barosl3** [comment]
:sunny: Test successful - [status](https://travis-ci.org/barosl2/test4/builds/77831857)

**Pull request merged**
