### PR TITLE
c

### PR DESCRIPTION
**Pull request by barosl2**

### CODE REVIEW

**Comment by barosl2** [comment]
@barosl3 r+

**Comment by barosl3** [comment]
:pushpin: Commit 59afeb4 has been approved by `barosl2`

**Comment by barosl3** [comment]
:hourglass: Testing commit 59afeb4 with merge c8e7a93...

**Comment by barosl3** [comment]
:sunny: Test exempt - [status](https://travis-ci.org/barosl2/test4/builds/88856927)

**Pull request merged**
